{
    'name': 'Customer Limit',
    'version': '1.0.0',
    'category': 'Customer Limit',
    'author':'odoo mates',
    'sequence':-400,
    'summary': 'Customer Limit',
    'description': """Customer Limit""",
    'depends':['base','sale','xlsx_reporting'],
    'data': ['security/ir.model.access.csv',
            'wizard/confirm_views.xml',
            'views/hold_view.xml',
             'views/res_partner_views.xml',
             'report/report_view.xml',
            ],
    'demo': [],           
    'installable': True,
    'application':True,
    'assets': {},
    'license': 'LGPL-3',
}